---
title: "HEP trends"
output: word_document
---

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

core.ardeids <- c("GBHE", "GREG", "SNEG", "BCNH")

full.names <- data.frame(spp.code = c("GBHE", "GREG", "SNEG", "BCNH"),
                         full.namess = c("Great Blue Herons", "Great Egrets", "Snowy Egrets", "Black-crowned Night-herons")) %>% 
  mutate(spp.code = as.character(spp.code),
         full.namess = as.character(full.namess))

hep.start <- read.csv("HEP_data/newer_hep.csv")
names(hep.start) <- tolower(names(hep.start))

hep <- hep.start %>% 
  filter(peakactvnsts > -1, year > 1989, year < 2015) %>% 
  mutate(code = as.numeric(as.character(code)))
rm(hep.start)
```

Number of colonies surveyed

```{r echo = FALSE, message = FALSE, warning = FALSE}

nba.num.co.per.year <- hep %>%
  select(code, year, species, peakactvnsts) %>% 
  group_by(year, species) %>% 
  summarise(num.col = n())
```



```{r echo = FALSE, message = FALSE, warning = FALSE}

ggplot(data = filter(nba.num.co.per.year, species %in% core.ardeids), aes(x = year, y = num.col, color = species)) +
  geom_point() +
  facet_wrap(~species) +
  theme(legend.position = "none") +
  ylab("# Colonies surveyed")

```

#--------------------------
Number of breeding pairs
```{r echo = FALSE, message = FALSE, warning = FALSE}

nba.breed.pop <- hep %>%
  select(code, year, species, peakactvnsts) %>% 
  group_by(year, species) %>% 
  summarise(yr.spp.tot.pop = sum(peakactvnsts)) %>% 
  data.frame()

nba.breed.pop.means <- nba.breed.pop %>% 
  filter(yr.spp.tot.pop > 0) %>% 
  group_by(species) %>% 
  summarize(mean.pop = round(mean(yr.spp.tot.pop), 0)) %>% 
  data.frame()

nba.breed.pop.max <- nba.breed.pop %>% 
  filter(yr.spp.tot.pop > 0) %>% 
  group_by(species) %>%
  filter(yr.spp.tot.pop == max(yr.spp.tot.pop)) %>% 
  data.frame()
  
nba.breed.pop.min <- nba.breed.pop %>% 
  filter(yr.spp.tot.pop > 0) %>% 
  group_by(species) %>%
  filter(yr.spp.tot.pop == min(yr.spp.tot.pop)) %>% 
  data.frame()

nba.breed.pop.years <- nba.breed.pop %>% 
  filter(yr.spp.tot.pop > 0) %>% 
  group_by(species) %>%
  summarize(first.year = min(year),
            last.year = max(year)) %>% 
  data.frame()
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
breed.pop.texter <- function(spp) {
spp.full.name <- full.names %>% filter(spp == spp.code) %>% select(full.namess)

breed.pop.lm <- lm(yr.spp.tot.pop ~ year, data = filter(nba.breed.pop, species == spp))

paste("Between ", nba.breed.pop.years %>% filter(species == spp) %>% select(first.year), " and ", nba.breed.pop.years %>% filter(species == spp) %>% select(last.year), " there were an average of ", nba.breed.pop.means %>% filter(species == spp) %>% select(mean.pop), " ", spp.full.name, " (", spp, ") breeding pairs per year in the North Bay region. The maximum number of ", spp, " pairs was ", nba.breed.pop.max %>% filter(species == spp) %>% select(yr.spp.tot.pop), " in ", nba.breed.pop.max %>% filter(species == spp) %>% select(year), " and the minimum number of pairs was ", nba.breed.pop.min %>% filter(species == spp) %>% select(yr.spp.tot.pop), " in ", nba.breed.pop.min %>% filter(species == spp) %>% select(year), ". The long-term trend in number of ", spp, " breeding pairs was ", ifelse(breed.pop.lm$coefficients[2] > 0, "positive", "negative"), ", ", ifelse(breed.pop.lm$coefficients[2] > 0, "increasing", "decreasing"), " an average of ", round(breed.pop.lm$coefficients[2], 1), " pairs per year.", sep = "")
}
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
breed.pop.texter("GBHE")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
breed.pop.texter("GREG")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
breed.pop.texter("SNEG")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
breed.pop.texter("BCNH")
```


```{r echo = FALSE, message = FALSE, warning = FALSE}
ggplot(data = filter(nba.breed.pop, species %in% core.ardeids), aes(x = year, y = yr.spp.tot.pop, color = species)) +
  geom_point() +
  facet_wrap(~species) +
  theme(legend.position = "none") +
  ylab("# Breeding pairs") +
  stat_smooth(method = "lm")
```


#---------------

Breeding productivity

```{r echo = FALSE, message = FALSE, warning = FALSE}

nba.productivity1 <- hep %>%
  select(code, year, species, peakactvnsts, contains("brd"), focalnests, focfailure) %>%
  mutate(num.chx = (brd1 * 1) + (brd2 * 2) + (brd3 * 3) + (brd4 * 4) + (brd5 * 5) + (brd6 * 6),
         nests4brd = (brd1 + brd2 + brd3 + brd4 + brd5 + brd6),
         #focfledge.match = ifelse(focalnests - focfailure == nests4brd, T, F),
         chx.per.fledg.nest = round(num.chx/nests4brd, 1),
         nest.succ = round((focalnests - focfailure)/focalnests, 2))

mean.chx.per.fledg.nest <- nba.productivity1 %>% 
  select(year, species, chx.per.fledg.nest) %>% 
  drop_na() %>% 
  group_by(year, species) %>% 
  summarise(mean.chx.per.fledg.nest = round(mean(chx.per.fledg.nest, rm.nan = T), 1)) %>% 
  arrange(year, species)

mean.nest.succ <- nba.productivity1 %>% 
  select(year, species, nest.succ) %>% 
  drop_na() %>% 
  group_by(year, species) %>% 
  summarise(mean.nest.succ = round(mean(nest.succ, rm.nan = T), 2)) %>% 
  arrange(year, species)

nba.productivity2 <- full_join(mean.chx.per.fledg.nest, mean.nest.succ) %>% 
  full_join(., nba.breed.pop) %>% 
  mutate(chx.per.nest = round(mean.chx.per.fledg.nest * mean.nest.succ, 1))
#---------
nba.productivity.mean <- nba.productivity2 %>%
  filter(chx.per.nest >= 0) %>% 
  group_by(species) %>% 
  summarize(mean.chx.per.nest = round(mean(chx.per.nest), 1)) %>% 
  data.frame()

nba.productivity.max <- nba.productivity2 %>%
  filter(chx.per.nest >= 0) %>% 
  group_by(species) %>%
  filter(chx.per.nest == max(chx.per.nest)) %>% 
  mutate(years = paste(year, collapse=", ")) %>%
  select(species, chx.per.nest, years) %>% 
  distinct() %>% 
  data.frame()

nba.productivity.min <- nba.productivity2 %>%
  filter(chx.per.nest >= 0) %>% 
  group_by(species) %>%
  filter(chx.per.nest == min(chx.per.nest))  %>% 
  mutate(years = paste(year, collapse=", ")) %>%
  select(species, chx.per.nest, years) %>% 
  distinct() %>% 
  data.frame() %>% 
  data.frame()

nba.productivity.years <- nba.productivity2 %>% 
  group_by(species) %>%
  summarize(first.year = min(year),
            last.year = max(year)) %>% 
  data.frame()

breed.prod.lm.gbhe <- lm(chx.per.nest ~ year, data = filter(nba.productivity2, species == "GBHE"))
breed.prod.lm.greg <- lm(chx.per.nest ~ year, data = filter(nba.productivity2, species == "GREG"))
breed.prod.lm.sneg <- lm(chx.per.nest ~ year, data = filter(nba.productivity2, species == "SNEG"))
breed.prod.lm.bcnh <- lm(chx.per.nest ~ year, data = filter(nba.productivity2, species == "BCNH", chx.per.nest >= 0))

```

```{r echo = FALSE, message = FALSE, warning = FALSE}

prod.summ.texter <- function(spp) {

spp.full.name <- full.names %>% filter(spp == spp.code) %>% select(full.namess)

breed.prod.lm <- lm(chx.per.nest ~ year, data = filter(nba.productivity2, species == spp, chx.per.nest >= 0))

paste("Between ", nba.productivity.years %>% filter(species == spp) %>% select(first.year), " and ", nba.productivity.years %>% filter(species == spp) %>% select(last.year), " ", spp.full.name, " (", spp, ") in the North Bay region produced an average of ", nba.productivity.mean %>% filter(species == spp) %>% select(mean.chx.per.nest), " fledged chicks per pair per year. The maximum number of fledged chicks per ", spp, " pair was ", nba.productivity.max %>% filter(species == spp) %>% select(chx.per.nest), " in ", nba.productivity.max %>% filter(species == spp) %>% select(years), " and the minimum number of chicks per pair was ", nba.productivity.min %>% filter(species == spp) %>% select(chx.per.nest), " in ", nba.productivity.min %>% filter(species == spp) %>% select(years), ". The long-term trend in number of chicks per GBHE breeding pair was ", ifelse(breed.prod.lm$coefficients[2] > 0, "positive", "negative"),", ", ifelse(breed.prod.lm$coefficients[2] > 0, "increasing", "decreasing"), " an average of ", round(breed.prod.lm$coefficients[2], 2), " chicks per pair per year.", sep = "")
}
```

```{r echo = FALSE, message = FALSE, warning = FALSE}

prod.summ.texter("GBHE")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}

prod.summ.texter("GREG")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}

prod.summ.texter("SNEG")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}

prod.summ.texter("BCNH")
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
ggplot(data = filter(nba.productivity2, species %in% core.ardeids), aes(x = year, y = chx.per.nest, color = species)) +
  geom_point() +
  facet_wrap(~ species) +
  theme(legend.position = "none") +
  ylab("# Chicks produced per nest") +
  stat_smooth(method = "lm")
